// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzflmkzdxalzgjhjwzwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6Zmxta3pkeGFsemdqaGp3endmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0OTg0NDUsImV4cCI6MjA2NzA3NDQ0NX0.sFrmElpkgdU2Tp8qW3-F_ASlILnWdhp4MvLHR-a-zfw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});